# Generated by Django 2.2.6 on 2019-12-19 00:28

import compositor.music.models.song
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mp3',
        ),
        migrations.AddField(
            model_name='song',
            name='ogg',
            field=models.FileField(blank=True, null=True, upload_to=compositor.music.models.song.generate_filename),
        ),
        migrations.AlterField(
            model_name='song',
            name='midi',
            field=models.FileField(default=None, upload_to='midi'),
            preserve_default=False,
        ),
    ]
